pragma Singleton
import QtQuick

// Material You palette, regenerated by matugen from the current wallpaper.
// Do not edit Colors.qml directly - edit this template instead.
//
// Properties that pair a surface with the color drawn on top of it use a
// "Text" suffix (e.g. primary/primaryText) rather than Material's "on"
// prefix, because QML reserves "on<Property>" for signal handlers whenever
// a sibling property named "<property>" exists on the same object.
QtObject {
    readonly property color primary: "#f9b1db"
    readonly property color primaryText: "#501e40"
    readonly property color primaryContainer: "#6a3458"
    readonly property color primaryContainerText: "#ffd8ec"

    readonly property color secondary: "#debece"
    readonly property color secondaryText: "#3f2a36"
    readonly property color secondaryContainer: "#57404d"
    readonly property color secondaryContainerText: "#fbd9ea"

    readonly property color tertiary: "#f4ba9e"
    readonly property color tertiaryText: "#4b2714"
    readonly property color tertiaryContainer: "#653d28"
    readonly property color tertiaryContainerText: "#ffdbcb"

    readonly property color error: "#ffb4ab"
    readonly property color errorText: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerText: "#ffdad6"

    readonly property color background: "#181115"
    readonly property color backgroundText: "#eddfe4"

    readonly property color surface: "#181115"
    readonly property color surfaceText: "#eddfe4"
    readonly property color surfaceVariant: "#4f4449"
    readonly property color surfaceVariantText: "#d3c2c9"
    readonly property color surfaceContainerLowest: "#130c10"
    readonly property color surfaceContainerLow: "#211a1d"
    readonly property color surfaceContainer: "#251e21"
    readonly property color surfaceContainerHigh: "#30282c"
    readonly property color surfaceContainerHighest: "#3b3236"

    readonly property color outline: "#9c8d93"
    readonly property color outlineVariant: "#4f4449"
    readonly property color shadow: "#000000"
    readonly property color scrim: "#000000"

    readonly property color inverseSurface: "#eddfe4"
    readonly property color inverseSurfaceText: "#362e32"
    readonly property color inversePrimary: "#854b70"
}
